// Terms of Use — the in-app rendering of docs/legal/terms-{he,en}.md. Keep this in sync with those
// files (they are the canonical reference for legal review). DRAFT: the operator name and jurisdiction
// are placeholders to fill before going live.
import type { Lang } from "./types";

export const TERMS_VERSION = "1.14";
export const TERMS_EFFECTIVE = "2026-09-22";

interface Section {
  heading: string;
  body: string;
}

const HE: Section[] = [
  { heading: "מהות השירות",
    body: "חברותא AI היא שותפה ללימוד תורה מבוססת בינה מלאכותית, המשיבה ממקורות מצוטטים (תנ\"ך, משנה, גמרא, ראשונים ופוסקים) הנשלפים ממאגר מקורות ייעודי. השירות נועד ללימוד, עיון והכנת שיעורים." },
  { heading: "אינו פסיקת הלכה",
    body: "התשובות והתכנים המופקים בשירות אינם פסיקת הלכה למעשה ואינם תחליף לרב מוסמך. יש לאמת כל מקור במקורו ולהיוועץ ברב מוסמך בכל שאלה הלכתית מעשית. אין להסתמך על השירות להכרעה הלכתית, ממונית או אישית." },
  { heading: "דיוק, אחריות והגבלת חבות",
    body: "התוכן נוצר באמצעות מערכות בינה מלאכותית ועלול לכלול שגיאות, אי-דיוקים או מידע חלקי. השירות ניתן \"כמות שהוא\" (AS IS), ללא כל אחריות מפורשת או משתמעת לדיוק, שלמות, אמינות או התאמה למטרה מסוימת. השימוש בשירות ובהסתמכות על תכניו נעשה על אחריותו הבלעדית של המשתמש.\n\nהגבלת חבות כספית: ככל שתוטל על המפעיל אחריות בדין בגין נזק הנובע מהשימוש בשירות או מהסתמכות על תכניו, תוגבל אחריותו הכוללת של המפעיל כלפי משתמש מסוים לסכום ששילם אותו משתמש בפועל עבור השירות בשלושת החודשים שקדמו לאירוע הנזק (ובמסלול החינמי — לסכום כולל שלא יעלה על 100 ₪), למעט במקרה של מעשה זדון או רשלנות רבתי מצד המפעיל, ובכפוף לכל הוראת דין קוגנטית." },
  { heading: "חשבון והרשמה, ואכיפה בהפרה",
    body: "עליך למסור כתובת אימייל תקינה ולשמור על סודיות פרטי הכניסה. אתה נושא באחריות המלאה לכל פעילות בחשבונך. בהפרה שאינה חמורה ניצור עמך קשר ונאפשר זמן סביר להסדרת ההתנהגות טרם נקיטת צעדים. הפרה חמורה (פגיעה באבטחה, גירוד אוטומטי, העלאת תוכן בלתי חוקי, עומס מכוון) עשויה להוביל לחסימה מיידית ללא התראה. השעיה עקב הפרה אינה מזכה בהחזר כספי. המפעיל שומר על זכותו לתבוע פיצוי על נזקים שינבעו משימוש לרעה." },
  { heading: "גיל — השירות מיועד לבני 18 ומעלה, ושיפוי מוסדי",
    body: "השירות מיועד למשתמשים בני 18 ומעלה בלבד, ואינו מיועד לקטינים. בעת ההרשמה נדרש אישור גיל מפורש. הרשמת קטין מהווה הפרה יסודית של התנאים וחשבון כזה ייסגר. האחריות להצהרת הגיל חלה על המשתמש בלבד.\n\nחשבונות מוסדיים ושיפוי: חשבון שנרכש עבור מוסד חינוכי מיועד לשימוש צוות ההוראה הבוגר בלבד. התלמידים אינם משתמשי השירות, וחל איסור מוחלט לפתוח חשבונות לתלמידים או להעביר להם פרטי גישה. מוסד חינוכי או מורה המאפשרים לתלמיד גישה לחשבון בניגוד להוראות אלה, יישאו במלוא האחריות הבלעדית לכל תוצאה, חשיפה או נזק הנובעים מכך, וישפו ויפצו את המפעיל בגין כל דרישה, נזק, הוצאה או תביעה מצד שלישי בעניין זה." },
  { heading: "תוכן שאתה מעלה, עיון ובדיקת תכנים",
    body: "בעת העלאת מקורות, קבצים או שאלות, אתה מצהיר שיש לך את מלוא הזכויות להתיר לנו ולספקינו לעבד אותם לצורך מתן השירות. חל איסור מוחלט להעלות תוכן בלתי חוקי, מפר זכויות יוצרים, פוגעני, או הפוגע בפרטיות של אחר. חל איסור מוחלט להעלות מידע סודי או פרטים אישיים מזהים.\n\nזכות עיון, ניטור ובדיקה של המפעיל: המפעיל וצוותו שומרים לעצמם את הזכות המלאה לעיין בהודעות, שאלות וקבצים המועלים למערכת — הן ידנית והן באמצעות מערכות אוטומטיות וכלי AI — לצורכי בקרת איכות, טיוב השירות, אימון מודלים, תמיכה טכנית, אבטחה ומניעת סיכוני לשון הרע. ככלל, עיון שגרתי נעשה ללא הצלבה יזומה מול פרטי החשבון המזהים שלך — הנשמרים אצל ספק ההרשמה בנפרד לחלוטין מתוכן ההודעות עצמו — אלא אם נדרש לצורך משפטי, תמיכה או בירור אבטחה. עם זאת, פרטים שתקליד בגוף ההודעה עצמה אינם מסוננים ומוצגים כפי שנכתבו.\n\nשמירת שיחות: שיחות שאינן פעילות נמחקות אוטומטית כעבור 90 יום בהתאם למדיניות הפרטיות. שיעורים שיצרת נשמרים בחשבונך. תוכן החשוב לטווח ארוך — עליך להוריד ולשמור עצמאית." },
  { heading: "שימוש הוגן",
    body: "חל איסור מוחלט לעשות שימוש לרעה בשירות, לרבות: עקיפת מכסות, גישה אוטומטית בלתי מורשית, גרימת עומס מכוון, הנדסה לאחור, או פגיעה בזמינות ובאבטחת השירות ומשתמשיו." },
  { heading: "קניין רוחני, מקורות ונוהל הודעה והסרה",
    body: "טקסטים ומקורות מתוך מאגר הספרות היהודית כפופים לרישיונות המקוריים שלהם (לרבות Creative Commons ודרישות ייחוס של מאגרים כגון Sefaria); הייחוס מוצג לצד המקור. הקוד, העיצוב, הממשק, סימני המסחר והאלגוריתמים של השירות שייכים באופן בלעדי למפעיל.\n\nנוהל הודעה והסרה לזכויות יוצרים: המפעיל מכבד את זכויות היוצרים של אחרים ופועל בהתאם לעקרונות הדין (\"הודעה והסרה\"). אם אתה סבור בתום לב כי תוכן מסוים המופיע בשירות, הועלה אליו או נשלף ממקורותיו מפר את זכויות היוצרים שלך, יש לפנות בדואר אלקטרוני לכתובת: rubinyehuda8@gmail.com בצירוף פירוט היצירה, זיהוי המיקום המפר וראיה לבעלותך בזכויות. עם קבלת פנייה מפורטת, המפעיל יבחן אותה ללא דיחוי ויפעל להסרת התוכן המפר בהתאם להוראות הדין." },
  { heading: "פרטיות, שימוש במידע ואימון מודלים",
    body: "אנו שומרים את פרטי החשבון, היסטוריית השיחות, השיעורים ונתוני המדידה. המידע משמש להפעלת השירות, וכן לצורכי מחקר, בקרת איכות, ואימון ופיתוח מודלים על ידי המפעיל ועל ידי ספקי בינה מלאכותית חיצוניים, הכל כמפורט במדיניות הפרטיות.\n\nמתגי החרגה (Opt-Out): ככל שהמשתמש מפעיל מתג החרגה (לשיחה בודדת או לחשבון כולו), ההחרגה מונעת אך ורק שימוש בשיחה לאימון מודלים פנימיים של המפעיל. ההחרגה אינה חלה על ספקי ה-AI החיצוניים (הפועלים לפי תנאיהם שלהם), ואינה מונעת מהמפעיל לעיין בשיחות לצורכי בקרת איכות, שיפור השירות, תמיכה ואבטחה.\n\nלא רטרואקטיבי — תיחום לפי מועד יצירת השיחה: השימוש בתוכן שיחות על ידי המפעיל חל אך ורק על שיחות שנוצרו מ-10.8.2026 ואילך. שיחה שנוצרה לפני מועד זה נשארת מוחרגת משימוש זה לצמיתות — גם אם התקבלה בה הודעה חדשה לאחר מכן." },
  { heading: "מכסות, תוכניות בתשלום וביטול מנוי",
    body: "השירות כולל תוכנית חינמית בעלת מכסה יומית ותוכניות מנוי בתשלום. המפעיל רשאי לעדכן מכסות ומחירים מעת לעת בהודעה סבירה מראש. המחירים המוצגים כוללים מע\"מ כחוק. כלל המנויים נגבים בתשלומים חודשיים שוטפים. ניתן לבטל מנוי בכל עת בלחיצה אחת (הגדרות → ביטול מנוי): החיוב הבא נפסק מיד והגישה נמשכת עד תום החודש ששולם. בעסקת מכר מרחוק ניתן לבטל תוך 14 יום ולקבל החזר בניכוי דמי ביטול כמותר בדין (5% או 100 ₪ — הנמוך מביניהם). מחיקת חשבון עוצרת את המנוי לאלתר.\n\nעצירת מענה יזומה (Stop Generation): שליחת שאלה או בקשה במערכת צורכת את המכסה או הקרדיט הנדרש עם תחילת הפעולה והעיבוד. עצירת מענה יזומה על ידי המשתמש במהלך הפקתו אינה מזכה בהחזר מכסה או קרדיטים." },
  { heading: "קופונים",
    body: "עשויים להיות מוצעים קופונים מעת לעת. קופון מקנה הטבה מסוימת (דרג תוכנית לתקופה מוגבלת או זיכויים). לקופון יש תאריך תפוגה והוא אינו ניתן להעברה. לקופון אין ערך כספי ואין אפשרות לפדות אותו במזומן. אם עסקה שנעשתה בקופון מבוטלת — ההטבה שניתנה בקופון נשללת." },
  { heading: "עוזרי פיתוח",
    body: "מעת לעת אנו מזמינים משתמשים לסייע בבדיקת השירות. ההשתתפות היא בהזמנה ובאישור מפורש שלך; עד שאישרת לא משתנה דבר בחשבונך, וניתן להפסיק בכל עת משני הצדדים. זו אינה עבודה ואינה יוצרת יחסי עובד-מעביד, שותפות או התקשרות עסקית — ההשתתפות התנדבותית ובלתי מתוגמלת, ואינך זכאי לשכר, לתמורה או לזכויות בשירות. מכסת השימוש בגובה התוכנית הבסיסית שמוקצית בזמן ההשתתפות היא הטבה ולא רכישה. יכולות שטרם שוחררו ניתנות כמות שהן ועשויות להשתנות או להיעלם ללא הודעה." },
  { heading: "ספקי המערכת ומפתח API אישי",
    body: "חופש פעולה בבחירת ספקים: השירות פועל באמצעות שילוב מערכות של ספקי צד שלישי — לרבות ספקי מודלי שפה ו-AI (כגון Nebius, OpenAI, Anthropic, Google Cloud וספקים דומים), ספקי מחשוב ענן ושרתים (כגון Hetzner, AWS, Google Cloud, Azure), ספקי בסיסי נתונים, ספקי אימות (Supabase) וספקי סליקה (PayPlus, חשבונית ירוקה). המפעיל שומר לעצמו את הזכות הבלעדית להחליף, להוסיף, להסיר או לנתב נתונים בין ספקים, מודלים ותשתיות בכל עת לפי שיקול דעתו הבלעדי, ללא צורך בהודעה מוקדמת, לצורך שיפור המענה, זמינות, אבטחה או ייעול עלויות.\n\nמפתח API אישי (BYOK): באפשרותך להזין מפתח API אישי משלך לצורך הפניית שאילתות ישירות לספק שבחרת. השימוש במפתח אישי הינו באחריותך הבלעדית ובכפוף לתנאים ולחיובים הישירים שבינך לבין אותו ספק. המפתח נשמר בדפדפן שלך בלבד ואינו מאוחסן בשרתינו." },
  { heading: "שינויים בתנאים",
    body: "אנו רשאים לעדכן תנאים אלה מעת לעת. המשך השימוש לאחר עדכון מהווה הסכמה לתנאים המעודכנים; הגרסה העדכנית תוצג תמיד בשירות." },
  { heading: "קהל היעד, דין וסמכות שיפוט",
    body: "השירות מוצע למשתמשים בישראל לפי הדין הישראלי, ואינו מכוון לתושבי האיחוד האירופי או שטחים אחרים עם דיני הגנת מידע נפרדים. על תנאים אלה, על מדיניות הפרטיות ועל כל סכסוך הנובע מהשירות יחול דין מדינת ישראל בלבד, וסמכות השיפוט הבלעדית תהיה של בתי המשפט המוסמכים במדינת ישראל. מבלי לגרוע מבלעדיות סמכות בתי המשפט, רשאים הצדדים להסכים בהסכמה הדדית ומפורשת בכתב להביא מחלוקת קונקרטית בפני בורר מוסכם או בית דין צדק (דין תורה)." },
  { heading: "יצירת קשר",
    body: "השירות מופעל על ידי יהודה רובין. לשאלות בנוגע לתנאים אלה: rubinyehuda8@gmail.com" },
];

const EN: Section[] = [
  { heading: "The Service",
    body: "Chavruta AI is an AI-based Torah study partner that answers with cited sources (Tanakh, Mishnah, Gemara, Rishonim and Poskim) retrieved from a dedicated source corpus. It is intended for study, review and lesson preparation." },
  { heading: "Not a Halachic Ruling",
    body: "Answers and content produced by the Service are not a halachic ruling and are no substitute for a qualified rabbi. Verify every source at its origin and consult a qualified rabbi on any practical halachic question. Do not rely on the Service for any halachic, financial, or personal decision." },
  { heading: "Accuracy, Warranty and Limitation of Liability",
    body: "Content is generated using artificial intelligence systems and may contain errors, inaccuracies, or incomplete information. The Service is provided \"AS IS\", without any warranty, express or implied, of accuracy, completeness, reliability, or fitness for a particular purpose. Use of the Service and reliance on its content is at the user's sole risk.\n\nMonetary limitation of liability: to the extent the operator is held liable under law for any damage arising from the use of the Service or reliance on its content, the operator's total liability to a given user shall be limited to the amount that user actually paid for the Service in the three months preceding the damaging event (or, under the free tier, to a total amount not exceeding ₪100), except in cases of willful misconduct or gross negligence by the operator, and subject to any overriding mandatory statutory provision." },
  { heading: "Account and Registration, and Enforcement of a Breach",
    body: "You must provide a valid email address and maintain the confidentiality of your login credentials. You bear full responsibility for all activity under your account. For a non-severe breach, we will contact you and allow reasonable time to rectify the conduct before taking further steps. A severe breach (security compromise, automated scraping, uploading unlawful content, deliberate overload) may lead to immediate suspension or closure without prior notice. Closure for a breach does not entitle you to a refund. The operator reserves the right to seek compensation for damage caused by misuse." },
  { heading: "Age — the Service Is for Users Aged 18 and Over, and Institutional Indemnity",
    body: "The Service is intended for users aged 18 and over only, and is not intended for minors. Registration requires an explicit age confirmation. Registering a minor constitutes a material breach of these terms and such an account will be closed. Responsibility for the age declaration rests solely with the user.\n\nInstitutional accounts and indemnity: an account contracted for an educational institution is intended for adult teaching staff only. Pupils are not users of the Service; creating accounts for pupils or sharing access credentials with them is strictly prohibited. An educational institution or teacher permitting a pupil access to an account in breach of these terms shall bear sole and exclusive responsibility for any outcome, exposure, or damage arising therefrom, and shall indemnify and hold harmless the operator against any claim, damage, expense, or third-party demand in this regard." },
  { heading: "Content You Upload, Inspection and Content Scanning",
    body: "When uploading sources, files (PDF, Word, text), or questions, you represent that you possess all necessary rights to permit us and our providers to process them to provide the Service. You must not upload unlawful, infringing, offensive, or privacy-violating content. Uploading confidential or personally identifiable information is strictly prohibited.\n\nOperator's right of inspection, monitoring and review: the operator and its team reserve the full right to inspect messages, questions, and uploaded files — both manually and using automated systems and AI tools — for quality review, service enhancement, model training, technical support, information security, and defamation risk prevention. Routine human review is performed without proactive cross-referencing against your identifying account details — which are kept separate by the registration provider — unless required for legal compliance, support, or security investigations. However, information you enter directly in the message body itself is not filtered and appears as written.\n\nConversation retention: inactive conversations are deleted automatically after 90 days in accordance with the Privacy Policy. Lessons you create are saved in your account. Content important to you for the long term should be downloaded and saved independently." },
  { heading: "Acceptable Use",
    body: "Misuse of the Service is strictly prohibited, including: circumventing quota limits, unauthorized automated access, causing deliberate server load, reverse engineering, or harming the security or availability of the Service or its users." },
  { heading: "Intellectual Property, Sources and Notice and Takedown Procedure",
    body: "Texts and sources from the Jewish bookshelf are subject to their original licenses (including Creative Commons licenses and attribution requirements of repositories such as Sefaria); applicable attribution is displayed beside each source. The code, design, interface, trademarks, and algorithms of the Service belong exclusively to the operator.\n\nNotice and Takedown procedure for copyright: the operator respects the intellectual property rights of others and operates under statutory Notice and Takedown principles. If you believe in good faith that content appearing on the Service, uploaded to it, or retrieved from its sources infringes your copyright, please notify us by email at rubinyehuda8@gmail.com with details of the copyrighted work, the infringing location on the Service, and proof of rights ownership. Upon receiving a detailed notice, the operator will review it promptly and act to remove or disable access to infringing content in accordance with applicable law." },
  { heading: "Privacy, Data Usage and Model Training",
    body: "We store account details, conversation history, lessons, and usage metrics. Data is used to operate the Service, and for research, quality control, and model training and development by the operator and external AI providers, as set out in full in the Privacy Policy.\n\nOpt-Out toggles: activating an opt-out toggle (for a single conversation or account-wide) prevents the conversation from being used for training the operator's internal models only. The opt-out toggle does not bind external AI providers (which operate under their own terms), and does not prevent the operator from inspecting conversations for quality control, enhancement, support, and security.\n\nNon-retroactivity — scoped by conversation creation date: use of conversation content by the operator applies strictly to conversations created from 10 August 2026 onward. A conversation created before that date remains permanently excluded from this use — even if a new message is received in it afterward." },
  { heading: "Quotas, Paid Plans and Cancellation",
    body: "The Service includes a free tier with a daily quota and paid subscription tiers. The operator may update quotas and prices from time to time with reasonable advance notice. Displayed prices include VAT. All subscriptions are billed in recurring monthly instalments. You may cancel at any time in one click (Settings → Cancel subscription): the next charge stops immediately and access continues until the end of the month you paid for. On a distance contract you may cancel within 14 days for a refund less the statutory fee (5% or ₪100, whichever is lower). Account deletion halts recurring billing immediately.\n\nStop Generation: stopping an in-progress response does not entitle you to a quota or credit refund, as model processing is consumed at the initiation of the request." },
  { heading: "Coupons",
    body: "Coupons granted from time to time provide a specific time-limited benefit. Coupons have no cash value, are non-transferable, and cannot be redeemed for cash. Cancelling a transaction revokes coupon benefits." },
  { heading: "Development Helpers",
    body: "Users invited to help test the Service participate voluntarily and without compensation. Participation creates no employment relationship or business entity, and grants no wages or intellectual property rights. Quota benefits are temporary and revocable by either party at any time. Pre-release capabilities are provided \"AS IS\"." },
  { heading: "System Providers and Bring Your Own Key (BYOK)",
    body: "Flexibility in choosing providers: the Service operates through a combination of third-party systems — including AI and language model providers (such as Nebius, OpenAI, Anthropic, Google Cloud, and similar providers), cloud infrastructure and server providers (such as Hetzner, AWS, Google Cloud, Azure), databases, authentication (Supabase), and billing providers (PayPlus, Green Invoice). The operator reserves the exclusive right to replace, add, remove, or route data between providers, models, and infrastructure at any time at its sole discretion, without prior notice, for service enhancement, availability, security, or cost efficiency.\n\nBring Your Own Key (BYOK): you may enter your own personal API key to direct queries to a provider of your choice. Using your own key is at your sole responsibility and subject to your direct agreement and costs with that provider. The key is stored in your browser only and is not stored on our servers." },
  { heading: "Changes to These Terms",
    body: "We may update these terms from time to time. Continued use of the Service after publication of updated terms constitutes acceptance. The current version is always shown in the Service." },
  { heading: "Intended Audience, Governing Law and Jurisdiction",
    body: "The Service is offered and designed for users in Israel under Israeli law, and is not directed at users in the European Union or other separate regulatory jurisdictions. These terms, the Privacy Policy, and any dispute arising from the use of the Service shall be governed exclusively by the laws of the State of Israel, and exclusive jurisdiction shall lie with the competent courts of the State of Israel. Without derogating from the exclusive jurisdiction of the courts, the parties may mutually and expressly agree in writing to refer a specific dispute for resolution before an agreed arbitrator or a Rabbinical court (Beit Din)." },
  { heading: "Contact",
    body: "The Service is operated by Yehuda Rubin. Questions about these terms: rubinyehuda8@gmail.com" },
];

export function termsSections(lang: Lang): Section[] {
  return lang === "en" ? EN : HE;
}

// ── Privacy Policy (mirrors docs/legal/privacy-{he,en}.md) ────────────────────
export const PRIVACY_VERSION = "1.11";
export const PRIVACY_EFFECTIVE = "2026-09-22";

const PRIVACY_HE: Section[] = [
  { heading: "איזה מידע אנו אוספים ועיון בו",
    body: "פרטי חשבון: כתובת האימייל שלך, המנוהלת דרך ספק ההרשמה Supabase (איננו רואים או שומרים את סיסמתך), ואישורי התנאים והגיל שניתנו בהרשמה ומועדם.\n\nתוכן שאתה יוצר וזכות עיון של המפעיל: שאלותיך, היסטוריית השיחות, השיעורים השמורים, ומקורות או קבצים שתצרף. המפעיל וצוותו שומרים לעצמם את הזכות המלאה לעיין במידע זה ובתוכן השיחות — הן לצורכי בקרת איכות, טיוב השירות, מחקר ואימון מודלים, והן לצורכי תמיכה טכנית, ניפוי שגיאות, אבטחת מידע ומניעת תוכן אסור.\n\nאופן העיון האנושי ואזהרת תוכן גולמי: ככל שמתבצע עיון אנושי בשיחות (לצורכי בקרת איכות, שיפור ואימון), תכליתו אינה זיהוי המשתמש, והוא נעשה ללא הצלבה יזומה מול פרטי החשבון המזהים שלך — הנשמרים אצל ספק ההרשמה בנפרד לחלוטין מתוכן השיחה עצמו. הצלבה עם פרטי החשבון תיעשה אך ורק כאשר הדבר יידרש לצורך משפטי, מענה לפנייה או תלונה שלך, טיפול באירוע אבטחה חמור, או איתור שימוש לרעה. שים לב: המערכת אינה מסננת אוטומטית מידע אישי שנכתב על ידך בתוך גוף ההודעה עצמה — כל פרט שתקליד בהודעה יוצג כפי שנכתב, ולפיכך חל איסור לכלול פרטים אישיים או רגישים בשאלות ובקבצים.\n\nסריקה וניטור תכנים: הודעות וקבצים עשויים לעבור סריקה אוטומטית (באמצעות מודלי AI ומערכות סיווג) וכן בדיקה ידנית, לאיתור פעילות אסורה, אלימות, פגיעה בפרטיות או סיכוני לשון הרע. באפשרותך גם לדגול תשובה לבדיקה ידנית יזומה.\n\nנתוני שימוש, מדידה ולוגים: מועדי פניות, שפה, כמות טוקנים, זמני עיבוד, רשומות שגיאה, כתובת IP ומזהה בקשה. עוזרי פיתוח: למשתתפים בתוכנית נשמרת רשומה ייעודית (מזהה חשבון, מועדים, יכולות שנפתחו, הערת סימון והודעות מערכת). העדפות מקומיות ומפתח אישי (BYOK) נשמרים בדפדפן בלבד ואינם מאוחסנים בשרתינו. נתוני מנוי וחיוב מנוהלים דרך ספקי הסליקה והחשבוניות." },
  { heading: "כיצד אנו משתמשים במידע",
    body: "אנו משתמשים במידע לתפעול השירות, הפקת תשובות ושיעורים, אכיפת מכסות, מתן תמיכה ואבטחת המערכת. איננו מוכרים את המידע שלך לצדדים שלישיים לצרכים פרסומיים.\n\nשיפור, מחקר ואימון מודלים על ידי המפעיל: אנו רשאים להשתמש בתוכן השיחות, השאלות והקבצים שהועלו לצורכי מחקר, בקרת איכות, וכן לצורך פיתוח, אימון, כוונון (Fine-Tuning) והערכה של מודלי שפה, אלגוריתמים ומערכות בינה מלאכותית של המפעיל. שימוש זה חל כברירת מחדל, ובכפוף למנגנון ההחרגה הפנימי המפורט בסעיף 12.\n\nלא רטרואקטיבי — תיחום לפי מועד יצירת השיחה: שימוש זה על ידי המפעיל חל אך ורק על שיחות שנוצרו מ-10.8.2026 ואילך. שיחה שנוצרה לפני מועד זה נשארת מוחרגת ממנו לצמיתות — גם אם התקבלה בה הודעה חדשה לאחר מכן." },
  { heading: "עיבוד ואימון על ידי ספקי בינה מלאכותית חיצוניים (צד שלישי)",
    body: "לצורך עיבוד השאלות והפקת מענה, שאלתך והמקורות שצירפת מועברים לספקי מודלי שפה ובינה מלאכותית חיצוניים.\n\nאימון מודלים על ידי הספקים: בהתאם לתנאי השימוש ומדיניות הפרטיות של ספקי הבינה המלאכותית השונים, ספקים אלה עשויים לשמור את הנתונים המועברים אליהם ולהשתמש בהם לצורך מחקר, פיתוח ואימון של מודלי הבינה המלאכותית שלהם. למפעיל אין שליטה על מדיניות הספקים ואיננו מתחייבים לאי-אימון מצדם במסגרת השירות הרגיל.\n\nכלל הברזל — מה שלא הוזן, לא נשלח: אין להזין בשירות מידע רגיש, סודי, פרטים אישיים מזהים, או מידע המוגן לפי דין. השימוש בשירות מהווה הסכמה להעברת המידע ועיבודו אצל אותם ספקים. אם בחרת להשתמש במפתח API אישי (BYOK), המידע מועבר ישירות מול חשבונך אצל הספק, בכפוף להסכם הישיר בינך לבינו." },
  { heading: "שיתוף מידע וספקי משנה",
    body: "איננו מוכרים את המידע שלך. אנו נעזרים בספקי שירות חיצוניים בכל תחומי הפעילות. המפעיל שומר לעצמו את הזכות לבחור, להחליף, להוסיף, להסיר או לנתב נתונים בין ספקים בכל עת לפי שיקול דעתו הבלעדי: ספקי בינה מלאכותית ומודלי שפה (כגון Nebius, OpenAI, Anthropic, Google Cloud ודומיהם); ספקי אירוח ענן, שרתים ותשתיות (כגון Hetzner, AWS, Google Cloud, Azure, Nebius); ספקי אימות וחשבונות (Supabase); ספקי סליקה וחשבונאות (PayPlus, חשבונית ירוקה); ספקי ניטור ולוגים; וספקי תמיכה ותקשורת. מקורות הלימוד נשלפים ממאגרים דיגיטליים (לרבות Sefaria). נחשוף מידע ככל שיידרש על פי צו שיפוטי, הוראת דין, או לצורך הגנה על זכויותינו המשפטיות." },
  { heading: "שמירת מידע",
    body: "שיחות: שיחה ללא פעילות במשך 90 יום נמחקת אוטומטית על הודעותיה. פנייה חדשה מאפסת את הספירה. שיעורים שיצרת נשמרים בחשבונך עד למחיקתם היזומה או סגירת החשבון. נתוני מדידה נשמרים לניתוח מגמות, ומנותקים מזהותך במחיקת חשבון. רשומות חיוב נשמרות בהתאם לחובות חשבונאיות בדין (כ-7 שנים). רשומות אבטחה ולוגים נשמרות לפרק זמן מוגבל לצורכי אבטחה ובקרה.\n\nעיון ושימוש לצורך בקרת איכות, שיפור ופיתוח מודלים חל רק על שיחות שנוצרו מ-10.8.2026 ואילך — לא רטרואקטיבית על שיחות קודמות, גם אם הן ממשיכות לקבל הודעות חדשות." },
  { heading: "הזכויות שלך",
    body: "באפשרותך לצפות ולמחוק שיחות ושיעורים מתוך האפליקציה. ניתן לבחור בהגדרות בין מחיקה בתום תקופת חסד (כ-30 יום, הניתנת לביטול) לבין מחיקה מיידית ללא אפשרות שחזור; בשני המקרים הנתונים נמחקים לצמיתות. מחיקת חשבון שבבעלותו מוסד פעיל תידחה עד לסגירת המוסד או העברת הבעלות. נשיב לבקשות עיון או תיקון מידע כנדרש בדין (תוך 30 יום, עם אפשרות הארכה ב-15 יום)." },
  { heading: "השירות אינו מיועד לקטינים",
    body: "השירות מיועד למשתמשים בני 18 ומעלה בלבד. ההרשמה מבוססת על הצהרת גיל מפורשת הנשמרת עם החשבון. איננו אוספים ביודעין מידע מקטינים; חשבון שיימצא כי נפתח בידי קטין ייסגר. בבתי ספר ובחשבונות מוסדיים: השירות בונה חומרי לימוד עבור תלמידים, אך התלמיד אינו משתמש במערכת — המורה הבגיר הוא שמפעיל אותה. חל איסור לפתוח חשבונות לתלמידים ואין להזין שמות או פרטים מזהים של תלמידים." },
  { heading: "עוגיות ואחסון מקומי",
    body: "אנו משתמשים באחסון מקומי בדפדפן להעדפות ממשק וניהול טוקן ההתחברות הפעיל. אין שימוש בעוגיות מעקב פרסומיות של צד שלישי." },
  { heading: "העברת מידע אל מחוץ לישראל",
    body: "ספקי המשנה שלנו מעבדים ומאחסנים נתונים בשרתים מחוץ לישראל — לרבות בארה\"ב, באיחוד האירופי ובאזורים שיפוטיים נוספים. השימוש בשירות מהווה הסכמה מפורשת להעברת המידע ועיבודו במדינות אלה, לפי תקנות הגנת הפרטיות (העברת מידע אל מאגרים מחוץ לגבולות המדינה), התשס\"א-2001, ובכפוף להתחייבויות חוזיות לאבטחת מידע." },
  { heading: "אבטחה",
    body: "אנו נוקטים אמצעי אבטחה סבירים (הצפנה בתעבורה, אימות והגבלות קצב) בהתאם לתקנות הגנת הפרטיות (אבטחת מידע), התשע\"ז-2017. אין באפשרותנו להבטיח אבטחה מוחלטת מפני פריצות בלתי מורשות." },
  { heading: "המאגר, מטרותיו והדין החל",
    body: "בעל המאגר ומנהלו: יהודה רובין, מפעיל השירות. מטרות המאגר: הפעלת השירות והפקת תשובות; שיוך שיחות ושיעורים; אכיפת מכסות ואבטחה; חיוב וחשבונאות; בקרת איכות ומחקר; ניטור אוטומטי וידני של תכנים למניעת פעילות אסורה ולשון הרע; ניתוח מדדי שימוש; פיתוח, אימון וטיוב מודלים של המפעיל (בכפוף לסעיף 12 ולתיחום הלא-רטרואקטיבי); עיבוד באמצעות ספקי משנה; וניהול תוכנית עוזרי הפיתוח. מדיניות זו נערכה לפי חוק הגנת הפרטיות, התשמ\"א-1981 (לרבות תיקון 13) והתקנות שמכוחו. זכות עיון ותיקון לפי הדין: הנך זכאי לעיין במידע שעליך המוחזק במאגר ולבקש את תיקונו או מחיקתו בהתאם להוראות סעיפים 13 ו-14 לחוק הגנת הפרטיות, כמפורט בסעיף 6 לעיל." },
  { heading: "מנגנון החרגת שיחות (Opt-Out)",
    body: "באפשרותך להחריג שיחה ספציפית או את כלל שיחותיך משימוש לצורכי אימון מודלים (באמצעות מתג בשיחה או בהגדרות).\n\nתחולת וגבולות ההחרגה — החרגה פנימית בלבד: הפעלת מתג ההחרגה מונעת אך ורק את הכללת תוכן השיחה במאגרי האימון והכוונון הפנימיים של מודלי הבינה המלאכותית של המפעיל. אינה מונעת אימון או עיבוד ע\"י ספקי ה-AI החיצוניים (הפועלים לפי מדיניותם העצמאית), ואינה גורעת מזכות העיון של המפעיל וצוותו לצורכי בקרת איכות, טיוב, תמיכה טכנית, אבטחת מידע ומניעת שימוש לרעה. בנוסף, שיחה שנוצרה לפני 10.8.2026 נשארת מוחרגת לצמיתות מעצם מועד יצירתה." },
  { heading: "שינויים ויצירת קשר",
    body: "אנו רשאים לעדכן מדיניות זו מעת לעת; הגרסה העדכנית תוצג תמיד בשירות. לשאלות ופניות בנושא פרטיות: rubinyehuda8@gmail.com" },
];

const PRIVACY_EN: Section[] = [
  { heading: "What We Collect and Inspection",
    body: "Account details: your email address, managed through Supabase (passwords are never seen or stored by us), and registration consents.\n\nContent you create and operator inspection: your questions, conversation history, saved lessons, and sources/files you attach. The operator and its team reserve the full right to inspect this content for quality review, service enhancement, research, and operator model training/fine-tuning, as well as for technical support, debugging, security, and abuse prevention.\n\nHuman review conduct and raw content warning: routine human review for quality and training is performed without proactive cross-referencing against your identifying account details, which are stored separately by the registration provider. Cross-referencing is performed only when required for legal compliance, user support, or security investigations. Notice: information you type inside the message body itself is not filtered and appears as written; do not include personal or sensitive details in questions or attached files.\n\nAutomated scanning: messages and files may undergo automated AI scanning and manual review to detect prohibited content or defamation risks. You can also flag answers for review. Usage, measurement and log data are kept for quotas, security, and optimization. Development helper records are kept for invited participants. Local preferences and BYOK API keys are stored in your browser only. Billing data is managed by payment and invoicing providers." },
  { heading: "How We Use It",
    body: "We use data to operate the Service, produce answers and lessons, enforce quotas, provide technical support, and secure the system. We do not sell your data for advertising.\n\nImprovement, research, and model training by the operator: we may use the content of conversations, questions, answers, and uploaded files for research, quality review, performance testing, and for developing, training, fine-tuning, and evaluating language models, algorithms, and AI systems of the operator. This use applies by default, subject to the internal opt-out mechanism in section 12.\n\nNon-retroactivity — scoped by conversation creation date: this use applies strictly to conversations created from 10 August 2026 onward. A conversation created before that date remains permanently excluded from this use — even if a new message is received in it afterward." },
  { heading: "Processing and Training by External AI Providers",
    body: "To process questions and generate responses, your questions and attached sources are transmitted to external AI and language model providers.\n\nModel training by providers: under the terms and privacy policies of the respective AI providers, these providers may retain transmitted data and use it for research, development, and training of their AI models. The operator does not control provider policies and does not warrant a no-training path under standard plans.\n\nGolden rule — what is not entered is not sent: do not enter sensitive, confidential, identifying personal information, or legally protected data into the Service. Using the Service constitutes express consent to data transmission and processing with these providers. If you use your own API key (BYOK), data is transmitted directly to your own account with the provider, governed by your direct agreement with that provider." },
  { heading: "Sharing and Sub-processors",
    body: "We do not sell your data. We engage trusted third-party service providers across all operational areas. The operator reserves the full right to select, replace, add, remove, or route data between providers at any time at its discretion: AI and language model providers (such as Nebius, OpenAI, Anthropic, Google Cloud, and similar providers); cloud hosting, server and infrastructure providers (such as Hetzner, AWS, Google Cloud, Azure, Nebius); authentication providers (Supabase); payment and invoicing providers (PayPlus, Green Invoice); logging and performance monitoring providers; and support providers. Study sources are retrieved from digital repositories (including Sefaria). We will disclose information if required by court order, statutory obligation, or to protect our legal rights." },
  { heading: "Retention",
    body: "Conversations: a conversation with no activity for 90 days is deleted automatically with its messages. A new message resets the count. Lessons you create are retained until deleted by you or account closure. Measurement data is kept for trend analysis, detached from your identity upon account deletion. Billing records are retained as required by statutory accounting obligations (approx. 7 years). Security logs are kept for a limited period.\n\nInternal review and training applies only to conversations created from 10 August 2026 onward, not retroactively to earlier conversations, even if they receive new messages." },
  { heading: "Your Rights",
    body: "You can view and delete conversations and lessons within the app. You can choose in Settings between deletion at the end of a grace period (approx. 30 days, cancellable) and immediate deletion without recovery; in both cases all data is permanently erased. Deletion of an account owning an active institution is refused until the institution is closed or transferred. We will respond to statutory access or correction requests as required by law (within 30 days, extendable by 15 days)." },
  { heading: "The Service Is Not Intended for Minors",
    body: "The Service is intended for users aged 18 and over only. Registration requires an explicit age declaration recorded with the account. We do not knowingly collect information from minors; an account found to belong to a minor will be closed. Schools and institutional accounts: the Service builds learning materials for pupils, but the pupil is not a user of the system. The user is the adult teacher. Opening pupil accounts or entering identifying pupil details is strictly prohibited." },
  { heading: "Cookies and Local Storage",
    body: "We use browser local storage for interface preferences and active session token management. We do not use third-party tracking cookies for advertising." },
  { heading: "Transfer of Data Outside Israel",
    body: "Our sub-processors process and store data on servers located outside Israel — including in the United States, European Union member states, and other jurisdictions globally. Using the Service constitutes express consent to data transfer, storage, and processing in these countries, in accordance with the Protection of Privacy Regulations (Transfer of Data to Databases Abroad), 2001, subject to contractual commitments to standard data security safeguards." },
  { heading: "Security",
    body: "We take reasonable security measures (encryption in transit, authentication, and rate limiting) in accordance with the Protection of Privacy (Data Security) Regulations, 2017. However, no system is impenetrable and we cannot guarantee absolute security against unauthorized intrusions." },
  { heading: "The Database, Its Purposes, and the Applicable Law",
    body: "Database owner and manager: Yehuda Rubin, operator of the Service. Purposes of the database: operating the Service and generating answers; associating conversations and lessons; enforcing quotas and security; billing and accounting; quality review and research; automated and manual content monitoring to prevent prohibited activities and defamation; analyzing usage metrics; developing, training, and fine-tuning operator models (subject to section 12 and the non-retroactive scope); processing via sub-processors; and running the development helpers programme. This policy is drawn up under the Protection of Privacy Law, 5741-1981 (including Amendment 13) and the regulations thereunder. Statutory rights of access and correction: you are entitled to inspect information about you held in the database and to request its correction or deletion in accordance with sections 13 and 14 of the Protection of Privacy Law, as set out in section 6 above." },
  { heading: "Opt-Out Mechanism",
    body: "You may exclude a specific conversation or all of your conversations from being used for model training (via a toggle in the conversation or in Settings).\n\nScope and limits of the exclusion — internal exclusion only: activating the toggle prevents the conversation from being included in the internal training and fine-tuning datasets of the operator's AI models. It does not prevent training or processing by external AI providers (which operate under their own policies), and does not limit the operator and its team from reviewing conversations for quality review, refinement, technical support, information security, and abuse prevention. Conversations created before 10 August 2026 remain excluded permanently by virtue of their creation date." },
  { heading: "Changes and Contact",
    body: "We may update this policy from time to time; the current version is always displayed in the Service. For privacy inquiries: rubinyehuda8@gmail.com" },
];

export function privacySections(lang: Lang): Section[] {
  return lang === "en" ? PRIVACY_EN : PRIVACY_HE;
}

// ── Accessibility Statement (mirrors docs/legal/accessibility-{he,en}.md) ─────
export const ACCESSIBILITY_VERSION = "1.1";
export const ACCESSIBILITY_EFFECTIVE = "2026-08-02";

const ACCESSIBILITY_HE: Section[] = [
  { heading: "מחויבותנו לנגישות",
    body: "חברותא AI פועלת להנגיש את השירות לאנשים עם מוגבלויות, ולאפשר שימוש נוח ושוויוני ככל הניתן. אנו עובדים לפי עקרונות תקן הנגישות לתכנים באינטרנט (WCAG) ברמה סבירה למוצר בשלב זה, ומשפרים את הנגישות באופן הדרגתי ומתמשך." },
  { heading: "מצב הנגישות הנוכחי",
    body: "השירות תומך, בין היתר, בניווט מקלדת בסיסי, בתמיכה בטכנולוגיות מסייעות נפוצות, ובתצוגה בעברית (RTL) ובאנגלית (LTR). בנוסף, כפתור הנגישות הצף (בפינת המסך) מאפשר להגדיל את גודל הטקסט, להפעיל ניגודיות גבוהה, להדגיש קישורים בקו תחתון ולעצור אנימציות — וההגדרות נשמרות באופן קבוע במכשיר. זהו מוצר חדש וקטן, ועדיין ייתכנו חלקים שאינם נגישים באופן מלא. אנו פועלים לאתר ולתקן פערים אלה ככל שהמוצר גדל." },
  { heading: "פנייה בנושאי נגישות",
    body: "נתקלת בבעיית נגישות בשימוש בשירות? נשמח שתפנה אלינו — רכז הנגישות: יהודה רובין, rubinyehuda8@gmail.com — ונשתדל להשיב ולטפל בפנייה בזמן סביר." },
  { heading: "שינויים בהצהרה",
    body: "הצהרה זו עשויה להתעדכן מעת לעת ככל שהנגישות משתפרת; הגרסה העדכנית תוצג תמיד בשירות." },
];

const ACCESSIBILITY_EN: Section[] = [
  { heading: "Our Commitment to Accessibility",
    body: "Chavruta AI works to make the Service accessible to people with disabilities, and to enable comfortable and equal use as far as reasonably possible. We follow the principles of the Web Content Accessibility Guidelines (WCAG) at a reasonable level for a product at this stage, and we improve accessibility gradually and on an ongoing basis." },
  { heading: "Current Accessibility Status",
    body: "The Service supports, among other things, basic keyboard navigation, support for common assistive technologies, and display in both Hebrew (RTL) and English (LTR). In addition, the floating accessibility button (in the corner of the screen) lets you increase text size, turn on high contrast, underline links, and stop animations — these settings are saved persistently on your device. This is a new, small product, and some parts may not yet be fully accessible. We work to identify and fix such gaps as the product grows." },
  { heading: "Contact Us About Accessibility",
    body: "Encountered an accessibility issue while using the Service? We'd welcome you contacting us — Accessibility Coordinator: Yehuda Rubin, rubinyehuda8@gmail.com — and we will do our best to respond and address it within a reasonable time." },
  { heading: "Changes to This Statement",
    body: "This statement may be updated from time to time as accessibility improves; the current version is always shown in the Service." },
];

export function accessibilitySections(lang: Lang): Section[] {
  return lang === "en" ? ACCESSIBILITY_EN : ACCESSIBILITY_HE;
}
